### ISSUE TITLE
earc jobs not archiving expected files

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1622]
**Expected behavior**
enkfgdasearc jobs should archive more than just enkfgdas log files and recenered analysis increment files.
 
**Current behavior**
A Hera parallel using current head of develop is only archiving enkfgdas log files in `enkfgdas.tar` and recentered analysis increments in `enkfgdas_grp*tar`.

**Machines affected**
Parallel run on Hera

**To Reproduce**
Install g-w and run a parallel with enkfgdas active.  Check output from earc jobs.

**Detailed Description**
`exgdas_enkf_earch.sh` executes `hpssarch_gen.sh` to create a list of paths/files to archive.   A quick check of `hpssarch_gen.sh` suggests that the script not fully updated to the new GFS COM directory structure.   

For example, the `enkfgdas` section of `hpssarch_gen.sh` has the following for member atmf and sfcf files
```
          echo "${COM_ATMOS_ANALYSIS_MEM/${ROTDIR}\//}/${head}atmf00${FHR}.nc"
          if (( FHR == 6 )); then
            echo "${COM_ATMOS_ANALYSIS_MEM/${ROTDIR}\//}/${head}sfcf00${FHR}.nc"
          fi
```
Member forecasts are in `COM_ATMOS_HISTORY`, not `COM_ATMOS_ANALYSIS_MEM`

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Can you point me to a log on Hera? I also just hit some failing earc jobs in a test of my own on Hera overnight but in my log the error appears to be a different one. Wanna see if we're dealing with multiple issues or something similar. Thanks!

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA Can you point me to a log on Hera? I also just hit some failing earc jobs in a test of my own on Hera overnight but in my log the error appears to be a different one. Wanna see if we're dealing with multiple issues or something similar. Thanks!

/scratch2/NCEPDEV/stmp1/Russ.Treadon/comrot/prufscom/logs/2021122112/enkfgdasearc01.log

**Comment by KateFriedman-NOAA** [comment]
Ok, we hit different bugs (yours with IAU off and mine with IAU on). I'll open a separate issue for my bug.

Will see who will pick up this issue to resolve. Thanks for the log!

**Comment by WalterKolczynski-NOAA** [comment]
`COM_ATMOS_ANALYSIS` is being used for the atm and sfc files where is should be `COM_ATMOS_HISTORY`.

**Comment by KateFriedman-NOAA** [comment]
I replaced `COM_ATMOS_ANALYSIS_MEM` with `COM_ATMOS_HISTORY` in a copy of `ush/hpssarch_gen.sh` for the atmf and sfcf archival section. Also, included the fix for #1623 and reran a failing earc job on Hera. Both sets of fixes worked. See [this comment](https://github.com/NOAA-EMC/global-workflow/issues/1623#issuecomment-1551973709) and log in #1623 for more details.

I did not test for a `DOIAU=NO` configuration. @RussTreadon-NOAA can you try the diffs outlined in issue #1623 to confirm they also work for your situation?

**Comment by KateFriedman-NOAA** [comment]
I'm going to open a PR with these diffs if you want to grab them from there @RussTreadon-NOAA ...one moment...

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , I manually added your hpssarch_gen.sh changes to my HOMEgfs.   I reran earc00 and earc01 jobs.   The jobs ran to completion.  I see more files in the enkfgdas tarballs.   I need to carefully check the tarballs to ensure all the expected files are present.

**Comment by KateFriedman-NOAA** [comment]
Thanks for testing in your experiment @RussTreadon-NOAA ! Let me know if you see any further missing files.

PR inbound.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , both your `verfiles` and my `prufscom` are now experiencing failures in `gdasarch.log`.   For example, `/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/verfiles/logs/2022010212/gdasarch.log` contains

```
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf000.txt"
*** Warning: No matching names located for 'gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf000.txt'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf003.txt"
*** Warning: No matching names located for 'gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf003.txt'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf006.txt"
*** Warning: No matching names located for 'gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf006.txt'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf009.txt"
*** Warning: No matching names located for 'gdas.20220102/12/model_data/atmos/history/gdas.t12z.logf009.txt'
```
The log files in `/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/verfiles/gdas.20220102/12/model_data/atmos/history` are named differently.  The directory contains
```
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:43 gdas.t12z.atm.logf000.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:43 gdas.t12z.atm.logf001.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:44 gdas.t12z.atm.logf002.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:44 gdas.t12z.atm.logf003.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:45 gdas.t12z.atm.logf004.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:45 gdas.t12z.atm.logf005.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:46 gdas.t12z.atm.logf006.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:47 gdas.t12z.atm.logf007.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:47 gdas.t12z.atm.logf008.txt
  -rw-r--r-- 1 Kate.Friedman stmp        71 May 17 16:48 gdas.t12z.atm.logf009.txt
```
Is the addition of `atm` to the log file intentional?   If so, we need to update `hpssarch_gen.sh`.   

This is becoming a can of worms.

**Comment by WalterKolczynski-NOAA** [comment]
Log file names were updated to include 'atm' in #1509 to match the same change from UFS.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @WalterKolczynski-NOAA , for confirming this change is intentional.   Our archive gfs, gdas, and enkfgdas jobs are broken.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , earc00 has another problem.  `hpssarch_gen.sh` is looking for ensmean model forecasts in `ensstat/analysis/atmos`.   
```
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.atmf003.ensmean.nc"
*** Warning: No matching names located for 'enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.atmf003.ensmean.nc'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.sfcf003.ensmean.nc"
*** Warning: No matching names located for 'enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.sfcf003.ensmean.nc'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.atmf006.ensmean.nc"
*** Warning: No matching names located for 'enkfgdas.20220102/12/ensstat/analysis/atmos/enkfgdas.t12z.atmf006.ensmean.nc'
```
The forecast ensemble mean files are now in `ensstat/model_data/atmos/history`.    

 Sorry for the headaches this is causing.

**Comment by WalterKolczynski-NOAA** [comment]
Don't apologize, this is mostly my fault. Pushes incoming.

**Comment by WalterKolczynski-NOAA** [comment]
@RussTreadon-NOAA I've pushed updates that fix both the log file names and the paths to the mean/spread atm/sfc files. Haven't tested it though.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA and @WalterKolczynski-NOAA .   I refreshed my HOMEgfs on Hera with the changed files in PR #1626.   

A rerun of a failed gdasarch job still failed.   The reason for the failure is the subject of g-w issue #1454.   UFSDA ATM var does not create a gsistat file.   gdasarch failed with rc=72 because the gsistat file is missing
```
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gdas.20211221/18/analysis/atmos/gdas.t18z.gsistat"
*** Warning: No matching names located for 'gdas.20211221/18/analysis/atmos/gdas.t18z.gsistat'
```
I added a bogus gsistat file to the com directory and reran gdasarch.   The gdasarch job got further but died again with rc=72 errors.  

UFSDA ATM var does not use the following obs files or generate the following output files
```
    echo "${COM_OBS/${ROTDIR}\//}/${head}nsstbufr"
    echo "${COM_OBS/${ROTDIR}\//}/${head}prepbufr"
    echo "${COM_OBS/${ROTDIR}\//}/${head}prepbufr.acft_profiles"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}abias"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}abias_air"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}abias_int"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}abias_pc"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}dtfanl.nc"
    echo "${COM_ATMOS_ANALYSIS/${ROTDIR}\//}/${head}loginc.txt"
```
UFSDA ATM var generates radiance bias correction files but (1) the filenames are not GSI names and (2) the contents of the UFSDA ATM var radiance bias correction files differ from the GSI.  

One could populate `hpssarch_gen.sh` with UFSDA specific hacks but this leaves us with a confusing web of logical tests of flags and files.  Maintaining, testing, and debugging a hacked `hpssarch_gen.sh` could prove challenging.  It also sends the wrong message to developers - _keep adding hacks to `hpssarch_gen.sh` until it does what you want._

We need a more flexible way to specify which files and tarballs to write to HPSS.   Without this capability we can not move beyond basic plumbing tests for UFSDA cycling. 

Tagging @aerorahul , @CoryMartin-NOAA , and @guillaumevernieres for awareness.

**Comment by RussTreadon-NOAA** [comment]
Tests of the updated `JGDAS_ENKF_ARCHIVE` found a typo.   The job has

```
##############################################
# Set variables used in the script
##############################################
export CDUMP=${RUN/enkf}

YMD=${PDY} HH=${cyc} generate_com -rx COM_TOP
MEMDIR="ensstat" YMD=${PDY} HH=${cyc} generate_com -rx \
  COM_ATMOS_ANALYSIS_ENSSTAT:COM_ATMOS_ANALYSIS_TMPL
  COM_ATMOS_HISTORY_ENSSTAT:COM_ATMOS_HISTORY_TMPL
```

A `\` is missing at the end of the `COM_ATMOS_ANALYSIS_ENSSTAT` line.  This results in a runtime error
```
generate_com :: COM_ATMOS_ANALYSIS_ENSSTAT=/scratch2/NCEPDEV/stmp1/Russ.Treadon/comrot/prufscom/enkfgdas.20211221/18/ensstat/analysis/atmos
+ JGDAS_ENKF_ARCHIVE[15]: COM_ATMOS_HISTORY_ENSSTAT:COM_ATMOS_HISTORY_TMPL
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/check/jobs/JGDAS_ENKF_ARCHIVE: line 15: COM_ATMOS_HISTORY_ENSSTAT:COM_ATMOS_HISTORY_TMPL: command\
 not found
+ JGDAS_ENKF_ARCHIVE[1]: postamble JGDAS_ENKF_ARCHIVE 1684406710 127
```

I added the `\` to my working copy of `JGDAS_ENKF_ARCHIVE`.   The job ran to completion but generated rc=72 errors.   The following files were not found:  `enkfgdas.t18z.enkfstat` and `enkfgdas.t18z.gsistat.ensmean`.   UFSDA ATM ens does not create these files.   I created dummy files with these names and reran.   With the dummy files present earc00 ran to completion.
