### ISSUE TITLE
Add IODA-converted obs to experimental_obs for marine DA CI tests

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#4031]
### Machine

Orion/Hercules, Gaea-C6, Gaea-C5, Hera/Ursa, WCOSS2

### Start date

20210325/00

### End date

20210325/00

**EDIT - ADDITION:** Also `gdas.20211220`  `gdas.20211221` `gfs.20211220`  `gfs.20211221` in `/work/noaa/da/aeichman/comoutobs` if still possible

### Additional information

These are in preparation of the conversion to obsForge as the starting point for `prepoceanobs` instead of obsproc. The contents of `/work/noaa/da/aeichman/comoutobs/gdas.20210325` and `/work/noaa/da/aeichman/comoutobs/gfs.20210325` on Orion are to be overlaid onto `experimental_obs/gdas.20210325` and `experimental_obs/gfs.20210325` respectively

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Comment by AndrewEichmann-NOAA** [comment]
@DavidHuber-NOAA The contents of the source directory are still evolving, please hold off popuplating for the moment

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA No problem.  I will add the blocked label.  When everything is as it should be, please just let me know.

**Comment by AndrewEichmann-NOAA** [comment]
@DavidHuber-NOAA ok, should be ready to go

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA Can you open up permissions on `/work/noaa/da/aeichman/comoutobs`?  I cannot see into `aeichman` as I am not a member of `da`.

**Comment by apchoiCMD** [comment]
@DavidHuber-NOAA please use the obs from `/scratch3/NCEPDEV/da/common_obsForge` if it is not late-

**Comment by AndrewEichmann-NOAA** [comment]
> [@AndrewEichmann-NOAA](https://github.com/AndrewEichmann-NOAA) Can you open up permissions on `/work/noaa/da/aeichman/comoutobs`? I cannot see into `aeichman` as I am not a member of `da`.

Whoops, sorry, done.

**Comment by AndrewEichmann-NOAA** [comment]
> [@DavidHuber-NOAA](https://github.com/DavidHuber-NOAA) please use the obs from `/scratch3/NCEPDEV/da/common_obsForge` if it is not late-

@apchoiCMD Why use those? I'm trying to replicate what's been used for the CI so far.

**Comment by apchoiCMD** [comment]
@AndrewEichmann-NOAA Oh, I meant for those below;

/scratch3/NCEPDEV/da/common_obsForge/gfs.20210325
/scratch3/NCEPDEV/da/common_obsForge/gdas.20210325

If @DavidHuber-NOAA will copy them into glopara-

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA I need clarification on this task:

- Which location should I pull from: MSU or Ursa?
- Is the intent to replace the folders currently in `experimental_obs` or should the files therein be added to the existing `experimental_obs` directories?

**Comment by apchoiCMD** [comment]
@DavidHuber-NOAA Forget about a location that I pointed you- it will be much easier to use @AndrewEichmann-NOAA 's directories-

**Comment by DavidHuber-NOAA** [comment]
Thanks @apchoiCMD for the clarification.

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA Could you also open up `/work/noaa/da/aeichman`?

**Comment by AndrewEichmann-NOAA** [comment]
> [@AndrewEichmann-NOAA](https://github.com/AndrewEichmann-NOAA) Could you also open up `/work/noaa/da/aeichman`?

Done

**Comment by AndrewEichmann-NOAA** [comment]
> [@AndrewEichmann-NOAA](https://github.com/AndrewEichmann-NOAA) I need clarification on this task:
> 
> * Which location should I pull from: MSU or Ursa?
> * Is the intent to replace the folders currently in `experimental_obs` or should the files therein be added to the existing `experimental_obs` directories?

- MSU
- The files should be added to the existing directories

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA Thanks for the clarification.

I'm still having issues accessing the directories.  I will need execute and read permissions on all directories and read permissions on all files.  Here's what I would suggest running:

```bash
chmod o+rx /work/noaa/da/aeichman
find /work/noaa/da/aeichman/comoutobs -group da -type d -exec chmod o+rx {} +
find /work/noaa/da/aeichman/comoutobs -group da -type f -exec chmod o+r {} +
```

**Comment by AndrewEichmann-NOAA** [comment]
> [@AndrewEichmann-NOAA](https://github.com/AndrewEichmann-NOAA) Thanks for the clarification.
> 
> I'm still having issues accessing the directories. I will need execute and read permissions on all directories and read permissions on all files. Here's what I would suggest running:
> 
> chmod o+rx /work/noaa/da/aeichman
> find /work/noaa/da/aeichman/comoutobs -group da -type d -exec chmod o+rx {} +
> find /work/noaa/da/aeichman/comoutobs -group da -type f -exec chmod o+r {} +

I ran those, they have all rs now

**Comment by DavidHuber-NOAA** [comment]
All data has been pushed and synced to Hera/Ursa, MSU, Cactus, Dogwood, and C6.  Closing as complete.

**Comment by DavidHuber-NOAA** [comment]
Reopening.  On review, I see that the log files were not copied.  I'm working on this now.

**Comment by DavidHuber-NOAA** [comment]
The log files have now also been synched.  Closing.

**Comment by guillaumevernieres** [comment]
@DavidHuber-NOAA , the permissions for these new file needs to be open to "other" as well.
Here's an example of the permission of one of the newly added file:
 ```
-rw-r----- 1 role-global global 7899230 Sep 15 10:11 /work2/noaa/global/role-global/data/experimental_obs/gdas.20210325/00/ocean/adt/gdas.t00z.adt_rads_all.nc
```
could you `chmod o+r` to the new files?

**Comment by DavidHuber-NOAA** [comment]
Thanks for the reminder @guillaumevernieres.  I have opened up permissions on MSU, Cactus, Dogwood, Hera/Ursa, and C6.  Can you confirm the files are now readable?

**Comment by AndrewEichmann-NOAA** [comment]
@DavidHuber-NOAA It looks right but we're going to run the CI to be sure.

**Comment by DavidHuber-NOAA** [comment]
@AndrewEichmann-NOAA Sounds good.  Would you like me to open up a do-not-merge PR so we can do this in an automated way?

**Comment by AndrewEichmann-NOAA** [comment]
@DavidHuber-NOAA It should be ok as is, since the relevant g-w PR was merged.
